name: Awesome Bot

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: gem install awesome_bot
    - name: Run Awesome Bot
      run: awesome_bot README.md --request-delay 0.2 --allow-dupe --allow-redirect --white-list reddit.com,coq.inria.fr,sciencedirect.com
