name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  deploy-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Copy content to deploy
        run: |
          mkdir public
          cp README.md public/index.md
          cp coq-logo.svg public/
          echo 'theme: jekyll-theme-cayman' > public/_config.yml

      - name: Deploy to GitHub pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: public
          target_branch: gh-pages
          jekyll: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
